<?php

declare(strict_types=1);

namespace Drupal\ai_claude_agent_sdk_runner\Entity;

use Drupal\Core\Config\Entity\ConfigEntityBase;
use Symfony\Component\Yaml\Yaml;

/**
 * Defines the Agent Runner Skill config entity.
 *
 * Stores a Drupal Tool API tool converted to Claude Code SKILL.md format.
 * Auto-generated skills are regenerated when the source AiAgent is saved.
 * Manually edited skills (auto_generated = FALSE) are preserved.
 *
 * @ConfigEntityType(
 *   id = "agent_runner_skill",
 *   label = @Translation("Agent Runner Skill"),
 *   label_collection = @Translation("Agent Runner Skills"),
 *   label_singular = @Translation("agent runner skill"),
 *   label_plural = @Translation("agent runner skills"),
 *   handlers = {
 *     "list_builder" = "Drupal\ai_claude_agent_sdk_runner\AgentRunnerSkillListBuilder",
 *     "form" = {
 *       "edit" = "Drupal\ai_claude_agent_sdk_runner\Form\AgentRunnerSkillForm",
 *       "delete" = "Drupal\Core\Entity\EntityDeleteForm",
 *     },
 *   },
 *   config_prefix = "runner_skill",
 *   admin_permission = "administer claude agent sdk",
 *   entity_keys = {
 *     "id" = "id",
 *     "label" = "label",
 *     "uuid" = "uuid",
 *   },
 *   config_export = {
 *     "id",
 *     "label",
 *     "uuid",
 *     "agent_id",
 *     "source_tool_id",
 *     "description",
 *     "skill_body",
 *     "input_schema",
 *     "auto_generated",
 *   },
 *   links = {
 *     "collection" = "/admin/config/ai/claude-agent-sdk/runner-skills",
 *     "edit-form" = "/admin/config/ai/claude-agent-sdk/runner-skills/{agent_runner_skill}/edit",
 *     "delete-form" = "/admin/config/ai/claude-agent-sdk/runner-skills/{agent_runner_skill}/delete",
 *   },
 * )
 */
class AgentRunnerSkill extends ConfigEntityBase implements AgentRunnerSkillInterface {

  protected string $id = '';
  protected string $label = '';
  protected string $agent_id = '';
  protected string $source_tool_id = '';
  protected string $description = '';
  protected string $skill_body = '';
  protected array $input_schema = [];
  protected bool $auto_generated = TRUE;

  /**
   * {@inheritdoc}
   */
  public function getAgentId(): string {
    return $this->agent_id;
  }

  /**
   * {@inheritdoc}
   */
  public function getSourceToolId(): string {
    return $this->source_tool_id;
  }

  /**
   * {@inheritdoc}
   */
  public function getDescription(): string {
    return $this->description;
  }

  /**
   * {@inheritdoc}
   */
  public function getSkillBody(): string {
    return $this->skill_body;
  }

  /**
   * {@inheritdoc}
   */
  public function getInputSchema(): array {
    return $this->input_schema;
  }

  /**
   * {@inheritdoc}
   */
  public function isAutoGenerated(): bool {
    return $this->auto_generated;
  }

  /**
   * {@inheritdoc}
   */
  public function toSkillMd(): string {
    $frontmatter = [
      'name' => $this->id(),
      'description' => $this->description,
      'allowed-tools' => ['Bash'],
    ];
    $yaml = Yaml::dump($frontmatter, 2, 2);
    $output = "---\n" . $yaml . "---\n";
    if ($this->skill_body) {
      $output .= "\n" . $this->skill_body . "\n";
    }
    return $output;
  }

  /**
   * {@inheritdoc}
   */
  public function postSave($storage, $update = TRUE): void {
    parent::postSave($storage, $update);
    \Drupal::service('ai_claude_agent_sdk_runner.runner_skill_file_sync')
      ->syncToFilesystem($this);
  }

  /**
   * {@inheritdoc}
   */
  public static function postDelete($storage, array $entities): void {
    parent::postDelete($storage, $entities);
    $sync = \Drupal::service('ai_claude_agent_sdk_runner.runner_skill_file_sync');
    foreach ($entities as $entity) {
      $sync->removeFromFilesystem($entity);
    }
  }

}
