<?php

declare(strict_types=1);

namespace Drupal\ai_claude_agent_sdk_runner\Entity;

use Drupal\Core\Config\Entity\ConfigEntityInterface;

/**
 * Interface for Agent Runner Skill config entities.
 *
 * Runner skills are Drupal Tool API tools that have been converted to
 * Claude Code SKILL.md format for execution via the sidecar.
 */
interface AgentRunnerSkillInterface extends ConfigEntityInterface {

  /**
   * Gets the source AI Agent entity ID.
   */
  public function getAgentId(): string;

  /**
   * Gets the source Drupal Tool API plugin ID.
   */
  public function getSourceToolId(): string;

  /**
   * Gets the one-line description for SKILL.md frontmatter.
   */
  public function getDescription(): string;

  /**
   * Gets the full SKILL.md body content.
   */
  public function getSkillBody(): string;

  /**
   * Gets the preserved tool input schema.
   */
  public function getInputSchema(): array;

  /**
   * Whether this skill was auto-generated (vs manually edited by user).
   */
  public function isAutoGenerated(): bool;

  /**
   * Generates the full SKILL.md content from entity fields.
   */
  public function toSkillMd(): string;

}
