<?php

declare(strict_types=1);

namespace Drupal\ai_claude_agent_sdk_runner;

use Drupal\Core\Config\Entity\ConfigEntityListBuilder;
use Drupal\Core\Entity\EntityInterface;

/**
 * Provides a list builder for Agent Runner Skill entities.
 */
class AgentRunnerSkillListBuilder extends ConfigEntityListBuilder {

  /**
   * {@inheritdoc}
   */
  public function buildHeader(): array {
    $header['label'] = $this->t('Skill');
    $header['agent_id'] = $this->t('Agent');
    $header['source_tool_id'] = $this->t('Source Tool');
    $header['auto_generated'] = $this->t('Auto-generated');
    return $header + parent::buildHeader();
  }

  /**
   * {@inheritdoc}
   */
  public function buildRow(EntityInterface $entity): array {
    /** @var \Drupal\ai_claude_agent_sdk_runner\Entity\AgentRunnerSkillInterface $entity */
    $row['label'] = $entity->label();
    $row['agent_id'] = $entity->getAgentId();
    $row['source_tool_id'] = $entity->getSourceToolId();
    $row['auto_generated'] = $entity->isAutoGenerated() ? $this->t('Yes') : $this->t('No (manually edited)');
    return $row + parent::buildRow($entity);
  }

}
