<?php

declare(strict_types=1);

namespace Drupal\ai_claude_agent_sdk_runner\Form;

use Drupal\Core\Entity\EntityForm;
use Drupal\Core\Form\FormStateInterface;

/**
 * Form for editing Agent Runner Skill entities.
 *
 * Editing a skill sets auto_generated to FALSE, preventing overwrite on sync.
 */
class AgentRunnerSkillForm extends EntityForm {

  /**
   * {@inheritdoc}
   */
  public function form(array $form, FormStateInterface $form_state): array {
    $form = parent::form($form, $form_state);

    /** @var \Drupal\ai_claude_agent_sdk_runner\Entity\AgentRunnerSkillInterface $entity */
    $entity = $this->entity;

    $form['label'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Label'),
      '#default_value' => $entity->label(),
      '#required' => TRUE,
    ];

    $form['id'] = [
      '#type' => 'machine_name',
      '#default_value' => $entity->id(),
      '#disabled' => !$entity->isNew(),
      '#machine_name' => [
        'exists' => '\Drupal\ai_claude_agent_sdk_runner\Entity\AgentRunnerSkill::load',
      ],
    ];

    $form['description'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Description'),
      '#description' => $this->t('One-line description for SKILL.md frontmatter.'),
      '#default_value' => $entity->getDescription(),
      '#maxlength' => 255,
    ];

    $form['skill_body'] = [
      '#type' => 'textarea',
      '#title' => $this->t('Skill Body (Markdown)'),
      '#description' => $this->t('The SKILL.md body content. Editing this will prevent auto-regeneration on agent save.'),
      '#default_value' => $entity->getSkillBody(),
      '#rows' => 20,
    ];

    $form['metadata'] = [
      '#type' => 'details',
      '#title' => $this->t('Source Metadata'),
      '#open' => FALSE,
    ];

    $form['metadata']['agent_id_display'] = [
      '#type' => 'item',
      '#title' => $this->t('Source Agent'),
      '#markup' => $entity->getAgentId() ?: $this->t('N/A'),
    ];

    $form['metadata']['source_tool_id_display'] = [
      '#type' => 'item',
      '#title' => $this->t('Source Tool'),
      '#markup' => $entity->getSourceToolId() ?: $this->t('N/A'),
    ];

    $form['metadata']['auto_generated_display'] = [
      '#type' => 'item',
      '#title' => $this->t('Auto-generated'),
      '#markup' => $entity->isAutoGenerated() ? $this->t('Yes') : $this->t('No (manually edited)'),
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function save(array $form, FormStateInterface $form_state): int {
    /** @var \Drupal\ai_claude_agent_sdk_runner\Entity\AgentRunnerSkillInterface $entity */
    $entity = $this->entity;

    // Mark as manually edited if the user changed the skill body.
    if (!$entity->isNew()) {
      $entity->set('auto_generated', FALSE);
    }

    $status = $entity->save();

    $this->messenger()->addStatus($this->t('Saved runner skill %label.', [
      '%label' => $entity->label(),
    ]));

    $form_state->setRedirectUrl($entity->toUrl('collection'));
    return $status;
  }

}
